### ISSUE TITLE
System Crash on Newest Version, iOS 14.8

### ISSUE THREAD

**Issue by Meteony** [opa334/Choicy#49] opened 2024-12-09 08:04 UTC
Newest version (1.5.0) crashes the system upon injection.
Downgrading to an older version (1.4.10-3 specifically) resolves this issue.

**Comment by Bloom-Flowers** [comment] 2024-12-09 15:06
me too ios14.3

**Comment by sulthannafx** [comment] 2024-12-11 07:51
newest version not stable, make jb crash

**Comment by opa334** [comment] 2024-12-11 21:35
Works just fine for me on all versions I tested on, including 14.3 and 14.6.

There is really only one thing that could cause this, can you test if this build is better?

https://www.mediafire.com/folder/y7b73o5sftlio/choicy_test_build

**Comment by opa334** [comment] 2024-12-11 21:55
If that build does not work, please zip all .plists (no dylibs!) in /Library/MobileSubstrate/DynamicLibraries and send it here.

**Comment by Bloom-Flowers** [comment] 2024-12-13 07:47
> If that build does not work, please zip all .plists (no dylibs!) in /Library/MobileSubstrate/DynamicLibraries and send it here.

That still doesn't work，The following are all the plists I use，Thanks a lot
My phone system：14.3（iPhone 11）
My jailbreak choice：Taurine1.1.6（The version displayed in libhooker settings is 1.6.9-1）
[plist.zip](https://github.com/user-attachments/files/18122977/plist.zip)

**Comment by opa334** [comment] 2024-12-13 21:41
> > If that build does not work, please zip all .plists (no dylibs!) in /Library/MobileSubstrate/DynamicLibraries and send it here.
> 
> That still doesn't work，The following are all the plists I use，Thanks a lot My phone system：14.3（iPhone 11） My jailbreak choice：Taurine1.1.6（The version displayed in libhooker settings is 1.6.9-1） [plist.zip](https://github.com/user-attachments/files/18122977/plist.zip)

Still can't reproduce anything, please also send your /var/mobile/Library/Preferences/com.opa334.choicyprefs.plist

**Comment by Bloom-Flowers** [comment] 2024-12-14 06:02
> > > If that build does not work, please zip all .plists (no dylibs!) in /Library/MobileSubstrate/DynamicLibraries and send it here.
> > 
> > 
> > That still doesn't work，The following are all the plists I use，Thanks a lot My phone system：14.3（iPhone 11） My jailbreak choice：Taurine1.1.6（The version displayed in libhooker settings is 1.6.9-1） [plist.zip](https://github.com/user-attachments/files/18122977/plist.zip)
> 
> Still can't reproduce anything, please also send your /var/mobile/Library/Preferences/com.opa334.choicyprefs.plist

[com.opa334.choicyprefs.zip](https://github.com/user-attachments/files/18134471/com.opa334.choicyprefs.zip)

**Comment by opa334** [comment] 2024-12-15 00:01
> > > > If that build does not work, please zip all .plists (no dylibs!) in /Library/MobileSubstrate/DynamicLibraries and send it here.
> > > 
> > > 
> > > That still doesn't work，The following are all the plists I use，Thanks a lot My phone system：14.3（iPhone 11） My jailbreak choice：Taurine1.1.6（The version displayed in libhooker settings is 1.6.9-1） [plist.zip](https://github.com/user-attachments/files/18122977/plist.zip)
> > 
> > 
> > Still can't reproduce anything, please also send your /var/mobile/Library/Preferences/com.opa334.choicyprefs.plist
> 
> [com.opa334.choicyprefs.zip](https://github.com/user-attachments/files/18134471/com.opa334.choicyprefs.zip)

Still works for me :/

I will retry on my 14.3 Xs just to be sure.

**Comment by opa334** [comment] 2024-12-15 00:29
Finally seems to have reproduced it on my Xs.

**Comment by Bloom-Flowers** [comment] 2024-12-15 03:10
> Finally seem to have reproduced it on my Xs.

Thank you for your hard work, boss.
Please take the time to fix it, thank you very much～

**Comment by opa334** [comment] 2024-12-15 03:25
Submitted 1.5.1 with a fix for this, should be out tomorrow or the day after.

**Closed by opa334** 2024-12-15 03:25 UTC
